default: &default
  adapter: mysql2
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: pebble_fitness_uploader_development

test:
  <<: *default
  database: pebble_fitness_uploader_test

production:
